<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <groupId>org.dows.cloud</groupId>
    <artifactId>dows-rbac</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <!--<hrm.version>${revision}</hrm.version>
        <uim.version>1.0.0-SNAPSHOT</uim.version>
        <aac.version>1.0.0-SNAPSHOT</aac.version>
        <app.version>1.0.0-SNAPSHOT</app.version>-->
        <!--<aspect.version>1.9.21</aspect.version>-->
        <!--<mybatis-flex.ext.version>1.10.8.110</mybatis-flex.ext.version>-->
        <mybatis-flex.ext.version>1.10.8.110</mybatis-flex.ext.version>
        <spring-cloud-dependencies.version>2024.0.1</spring-cloud-dependencies.version>
        <jdk.version>21</jdk.version>
    </properties>


    <modules>
        <module>rbac-api</module>
        <module>rbac-app</module>
        <module>rbac-biz</module>
        <module>rbac-boot</module>
        <module>rbac-config</module>
        <module>rbac-feign</module>
        <module>rbac-handler</module>
        <module>rbac-pojo</module>
        <module>rbac-rest</module>
        <module>rbac-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-app</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-biz</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-boot</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-config</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-feign</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-handler</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-pojo</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-service</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rbac-rest</artifactId>
                <version>${project.version}</version>
            </dependency>


            <!--<dependency>
                <artifactId>uim-api</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${uim.version}</version>
            </dependency>-->

            <!--<dependency>
                <artifactId>aac-api</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${aac.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>app-api</artifactId>
                <version>${app.version}</version>
            </dependency>-->


            <!--<dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>-->

            <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
            <!--<dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.7.3</version>
            </dependency>-->


            <!--<dependency>
                <groupId>com.tangzc</groupId>
                <artifactId>mybatis-flex-ext-spring-boot3-starter</artifactId>
                <version>${mybatis-flex.ext.version}</version>
            </dependency>-->

        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <repository>
            <id>2290151-snapshot-aLhHBl</id>
            <url>https://packages.aliyun.com/634f4de0327f73640e96c28d/maven/2290151-snapshot-alhhbl</url>
        </repository>
        <snapshotRepository>
            <id>2290151-snapshot-aLhHBl</id>
            <url>https://packages.aliyun.com/634f4de0327f73640e96c28d/maven/2290151-snapshot-alhhbl</url>
        </snapshotRepository>
    </distributionManagement>
</project>
