server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
  #启用压缩
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
  servlet:
    #context-path: /${spring.application.name}
    encoding:
      charset: UTF-8

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 10001



---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
server:
  port: 20001


---
#测试环境
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 30001

---
#测试环境
spring:
  config:
    activate:
      on-profile: prd
server:
  port: 40001