spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      # 连接池允许的最大连接数
      maximum-pool-size: 100
      # 最小空闲线程数量
      minimum-idle: 10
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 多久检查一次连接的活性
      keepaliveTime: 30000
      # 配置获取连接等待超时的时间，单位毫秒
      connectionTimeout: 30000
      # 是否自动提交事务
      autoCommit: true
      # 用于测试连接是否有效的 SQL 查询语句
      connectionTestQuery: SELECT 1
      # 连接池的名称，用于日志和监控
      poolName: UimHikariCP

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://115.159.24.40:13306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: encrypted$HnOB7XSpPC5NvdV5HYhzAQ==
    password: encrypted$jwBBPVuexU/i22za5nVxCg==


---
#开发环境
spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:mariadb://115.159.24.40:13306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: encrypted$HnOB7XSpPC5NvdV5HYhzAQ==
    password: encrypted$jwBBPVuexU/i22za5nVxCg==

---
#开发环境
spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: jdbc:mariadb://192.168.111.103:3306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: rade
    password: rade123!

