rade:
  initialize:
    enabled: true
    initializers:
      - org.dows.rbac.handler.RbacUriInitializer
    resources:
      - initModel: never
        dataDir: /opt/rade/data
        initializer: org.dows.rbac.handler.RbacUriInitializer
        scanPackages: org.dows.rbac,org.dows.aac,org.dows.hrm,org.dows.uim

#      - initModel: always
#        initializer: org.dows.rbac.handler.RbacMenuInitializer
#        path: file://org.dows.rbac,org.dows.aac,org.dows.hrm,org.dows.uim