spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      connectionTimeout: 6000

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://192.168.111.103:13306/test?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: shdy123!


